(() => {
  const STORE='wm_v3';
  const getData=()=>{try{return JSON.parse(localStorage.getItem(STORE))||{workers:[],a:{},p:[]}}catch(e){return{workers:[],a:{},p:[]}}};
  const saveData=d=>{localStorage.setItem(STORE,JSON.stringify(d));localStorage.setItem(STORE+'_backup',JSON.stringify(d));location.reload()};
  const money=n=>Number(n||0).toLocaleString('en-IN');
  const info=()=>{const mo=document.getElementById('mo'),yr=document.getElementById('yr'),m=Number(mo?.value??new Date().getMonth()),y=Number(yr?.value??new Date().getFullYear()),days=new Date(y,m+1,0).getDate();return{m,y,days,prefix:`${y}-${String(m+1).padStart(2,'0')}-`,key:(id,d)=>`${id}|${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`}};
  const stats=w=>{const d=getData(),z=info();let present=0,absent=0,half=0;for(let day=1;day<=z.days;day++){const a=d.a?.[z.key(w.id,day)];if(a==='P')present++;if(a==='A')absent++;if(a==='H')half++}const salary=Number(w.salaryByMonth?.[`${z.y}-${String(z.m+1).padStart(2,'0')}`]||0),daily=salary/z.days,deduction=(absent+half/2)*daily,earned=Math.max(0,salary-deduction),paid=(d.p||[]).filter(x=>x.id===w.id&&String(x.date).startsWith(z.prefix)).reduce((s,x)=>s+Number(x.amount||0),0);return{z,present,absent,half,salary,daily,deduction,earned,paid,balance:earned-paid}};
  function editDaily(id){const d=getData(),w=d.workers.find(x=>x.id===id);if(!w)return;const v=prompt('Enter daily wage ₹:',w.rate||0);if(v===null)return;const n=Number(String(v).replace(/,/g,''));if(!Number.isFinite(n)||n<0)return alert('Enter a valid amount.');w.rate=n;saveData(d)}
  function editSalary(id){const d=getData(),w=d.workers.find(x=>x.id===id);if(!w)return;const z=info(),mk=`${z.y}-${String(z.m+1).padStart(2,'0')}`;if(!w.salaryByMonth)w.salaryByMonth={};const v=prompt(`Enter fixed monthly salary for ${mk}:`,w.salaryByMonth[mk]||0);if(v===null)return;const n=Number(String(v).replace(/,/g,''));if(!Number.isFinite(n)||n<0)return alert('Enter a valid salary amount.');w.salaryByMonth[mk]=n;saveData(d)}
  function enhanceWorkers(){const list=document.getElementById('wlist');if(!list)return;list.querySelectorAll('.worker').forEach(card=>{const profile=card.querySelector('button[onclick^="openProfile("]');if(!profile)return;const m=profile.getAttribute('onclick').match(/openProfile\((\d+)\)/);if(!m)return;const id=Number(m[1]);if(card.dataset.enhanced)return;card.dataset.enhanced='1';const edit=document.createElement('button');edit.textContent='✏️ Edit';edit.onclick=()=>{const d=getData(),w=d.workers.find(x=>x.id===id);if(!w)return;const name=prompt('Enter new worker name:',w.name);if(name===null)return;const clean=name.trim();if(!clean){alert('Worker name cannot be empty.');return}w.name=clean;saveData(d)};const del=document.createElement('button');del.textContent='🗑️ Delete';del.onclick=()=>{const d=getData(),w=d.workers.find(x=>x.id===id);if(!w)return;if(!confirm(`⚠️ Delete worker "${w.name}"?\n\nThis will permanently delete the worker and their attendance and payment history from this phone.\n\nAre you sure?`))return;d.workers=d.workers.filter(x=>x.id!==id);Object.keys(d.a||{}).forEach(k=>{if(k.startsWith(id+'|'))delete d.a[k]});d.p=(d.p||[]).filter(x=>x.id!==id);saveData(d)};profile.parentNode.insertBefore(edit,profile.nextSibling);profile.parentNode.appendChild(del)})}
  function enhanceProfile(){const box=document.getElementById('pstats'),title=document.getElementById('pname');if(!box||!title||!document.getElementById('profile')?.classList.contains('on'))return;const d=getData(),w=d.workers.find(x=>x.name===title.textContent);if(!w)return;const old=document.getElementById('profileSalaryExtra');if(old)old.remove();const s=stats(w);const extra=document.createElement('div');extra.id='profileSalaryExtra';extra.className='worker';extra.style.marginTop='10px';extra.innerHTML=`<div class="row"><b class="grow">💰 ${document.getElementById('mo')?.selectedOptions[0]?.text||''} ${s.z.y} Salary</b><button id="changeSalary">✏️ Salary</button></div><div class="small" style="margin-top:7px">Fixed monthly salary: <b>₹${money(s.salary)}</b></div><div class="small" style="margin-top:5px">Absent: ${s.absent} • Half days: ${s.half} • Deduction: <b>₹${money(s.deduction)}</b></div><div class="row" style="margin-top:8px"><b>Salary earned: ₹${money(s.earned)}</b><span class="grow"></span><b>Paid: ₹${money(s.paid)}</b></div><div style="margin-top:5px"><b>Remaining balance: ₹${money(s.balance)}</b></div><hr style="border:0;border-top:1px solid #eee;margin:12px 0"><div class="row"><b class="grow">Daily Wage</b><button id="changeDaily">✏️ Change</button></div><div style="margin-top:6px;font-size:18px"><b>₹${money(w.rate)}</b> <span class="small">per day</span></div>`;box.parentNode.insertBefore(extra,box.nextSibling);document.getElementById('changeSalary').onclick=()=>editSalary(w.id);document.getElementById('changeDaily').onclick=()=>editDaily(w.id)}
  const enhance=()=>{enhanceWorkers();enhanceProfile()};const obs=new MutationObserver(enhance);obs.observe(document.body,{childList:true,subtree:true});document.addEventListener('change',enhance);enhance();
})();